---
name: Check install

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Install plugin
        run: |-
          helm plugin install https://github.com/nhomble/helm-pull-exactly
